# Generated by Django 6.1.dev20260302190811 on 2026-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField(auto_now_add=True)),
                ('teplota', models.FloatField()),
                ('svetlo', models.FloatField()),
            ],
        ),
    ]
