# Generated by Django 6.1.dev20260302190811 on 2026-03-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pocasie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.DateTimeField()),
                ('teplota', models.FloatField()),
                ('tlak', models.FloatField()),
                ('vietor', models.FloatField()),
                ('o3', models.FloatField()),
                ('vlhkost', models.FloatField()),
                ('pocet', models.IntegerField()),
            ],
        ),
    ]
